"use client";

import { useState } from "react";

import { usePlatform } from "@/components/app/platform-provider";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import type { Zone } from "@/gen/dns/v1/dns_pb";
import type {
  CreateMailboxResponse,
  Mailbox,
  UpdateMailboxResponse,
} from "@/gen/mail/v1/mail_pb";
import { describeError } from "@/lib/errors";
import { plural } from "@/lib/format";
import { getMailClient } from "@/lib/platform-client";
import { formatBytes } from "@/lib/platform-model";

export type MailboxDialogProps = {
  zone: Zone;
  mode: "create" | "edit";
  /** The mailbox being edited; unset in "create" mode. */
  mailbox?: Mailbox;
  /** `MAIL_MAILBOXES_PER_DOMAIN`. */
  limit: number;
  /** Mailboxes already on this domain, for the "3 of 5 mailboxes used" note. */
  count: number;
  open: boolean;
  onOpenChange(open: boolean): void;
  /**
   * Called after a successful create/update. When supplied it is the ONLY state
   * transition the dialog makes — `onOpenChange(false)` is not called as well —
   * so a caller that stores the result (the one-time password) in the same state
   * variable that opens this dialog is not immediately reset. Such a caller must
   * therefore close the dialog itself when it has nothing further to show.
   */
  onDone?(result: CreateMailboxResponse | UpdateMailboxResponse): void;
};

const gib = BigInt(1024) * BigInt(1024) * BigInt(1024);
const quotas = [1, 5, 10, 25] as const;

const localPartPattern = /^[a-z0-9](?:[a-z0-9._+-]{0,62}[a-z0-9])?$/;

/**
 * Adds or edits one mailbox. The generated password is never shown here: `CreateMailbox`
 * returns it once and the caller hands it straight to `MailboxCreatedDialog`.
 */
export function MailboxDialog({
  zone,
  mode,
  mailbox,
  limit,
  count,
  open,
  onOpenChange,
  onDone,
}: MailboxDialogProps) {
  const { invalidate } = usePlatform();
  const [localPart, setLocalPart] = useState(mailbox?.localPart ?? "");
  const [displayName, setDisplayName] = useState(mailbox?.displayName ?? "");
  const [quota, setQuota] = useState(() => {
    const bytes = mailbox?.quotaBytes ?? BigInt(0);
    const found = quotas.find((gb) => BigInt(gb) * gib === bytes);
    return String(found ?? 5);
  });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>();

  const normalised = localPart.trim().toLowerCase();
  const localInvalid =
    normalised.length > 0 &&
    (!localPartPattern.test(normalised) || normalised.includes(".."));
  const atLimit = mode === "create" && limit > 0 && count >= limit;

  async function handleSubmit() {
    setError(undefined);
    setBusy(true);
    try {
      const quotaBytes = BigInt(Number(quota)) * gib;
      const result =
        mode === "create"
          ? await getMailClient().createMailbox({
              zoneId: zone.id,
              localPart: normalised,
              displayName: displayName.trim(),
              quotaBytes,
            })
          : await getMailClient().updateMailbox({
              zoneId: zone.id,
              mailboxId: mailbox?.id ?? "",
              displayName: displayName.trim(),
              quotaBytes,
            });
      await invalidate();
      // `onDone` owns the next state transition: the callers keep the created
      // mailbox's one-time password in the same state variable that drives this
      // dialog, so calling `onOpenChange(false)` here as well would reset it in
      // the same batch and the password screen would never mount.
      if (onDone) {
        onDone(result);
      } else {
        onOpenChange(false);
      }
    } catch (caught) {
      setError(describeError(caught));
      setBusy(false);
    }
  }

  if (!open) {
    return null;
  }

  return (
    <Dialog
      open
      onOpenChange={(next) => {
        if (!next && busy) {
          return;
        }
        onOpenChange(next);
      }}
    >
      <DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-md">
        <DialogHeader>
          <DialogTitle>
            {mode === "create"
              ? `Add a mailbox on ${zone.name}`
              : `Edit ${mailbox?.address ?? ""}`}
          </DialogTitle>
          <DialogDescription>
            {mode === "create"
              ? "The password is generated by the mail server and shown once, on the next screen."
              : "The address cannot be changed; add a forwarder instead."}
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-3">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="mailbox-local">Address</Label>
            <div className="flex items-center gap-1.5">
              <Input
                id="mailbox-local"
                value={localPart}
                onChange={(event) => setLocalPart(event.target.value)}
                placeholder="hello"
                autoComplete="off"
                autoCapitalize="none"
                spellCheck={false}
                disabled={busy || mode === "edit"}
                aria-invalid={localInvalid || undefined}
                className="font-mono text-[13px]"
              />
              <span className="font-mono text-[13px] text-muted-foreground">
                @{zone.name}
              </span>
            </div>
            {localInvalid ? (
              <p role="alert" className="text-xs text-destructive">
                Use letters, digits and . _ + - — starting and ending with a
                letter or digit.
              </p>
            ) : null}
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="mailbox-name">Display name</Label>
            <Input
              id="mailbox-name"
              value={displayName}
              onChange={(event) => setDisplayName(event.target.value)}
              placeholder="Mara Okonjo"
              autoComplete="off"
              maxLength={80}
              disabled={busy}
            />
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="mailbox-quota">Mailbox size</Label>
            <Select value={quota} onValueChange={setQuota} disabled={busy}>
              <SelectTrigger id="mailbox-quota" className="w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {quotas.map((gb) => (
                  <SelectItem key={gb} value={String(gb)}>
                    {formatBytes(BigInt(gb) * gib)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {limit > 0 ? (
            <p className="text-xs text-muted-foreground">
              {count} of {limit} {plural(limit, "mailbox", "mailboxes")} used.
            </p>
          ) : null}
          {atLimit ? (
            <p role="alert" className="text-xs text-warning">
              This domain has used every mailbox in the plan.
            </p>
          ) : null}

          {error ? (
            <p role="alert" className="text-xs text-destructive">
              {error}
            </p>
          ) : null}
        </div>

        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={busy}
          >
            Cancel
          </Button>
          <Button
            onClick={() => {
              void handleSubmit();
            }}
            disabled={
              busy ||
              localInvalid ||
              atLimit ||
              (mode === "create" && normalised.length === 0)
            }
          >
            {busy
              ? "Saving…"
              : mode === "create"
                ? "Create mailbox"
                : "Save changes"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
