apiVersion: v2
name: dns
description: A lightweight authoritative DNS hosting platform
type: application
version: 0.3.0
appVersion: "0.3.0"
kubeVersion: ">=1.27.0-0"
home: https://github.com/castlemilk/dns
sources:
  - https://github.com/castlemilk/dns
maintainers:
  - name: castlemilk
